### PR TITLE
JWT mods

### PR DESCRIPTION
**Pull request by mjheilmann**
This pull request includes the following two changes:

1 - Incoming JWT tokens have their signatures verified before they are decoded

2 - The module can now also decode modified base64 strings, which can come from other issuers such as nodejs.

### CODE REVIEW

**Comment by appurist** [comment]
This looks like an excellent update, some nice catches in here. Thanks!

I do have one question, about an `else` on the `HasValidSignature` check. My concern is that it leaves Payload set to the previous value, it should probably clear it, and `throw new JWTokenException("Invalid Signature");` or something like that?

**Comment by mjheilmann** [comment]
That `HasValidSignature` check occurs within the constructor so it will leave it uninitialized, which is null.

I think you are correct that throwing instead of setting a flag would be better.  I will make that change and examine both RemoteAdmin and RemoteConsole where it is used.

**Comment by appurist** [comment]
Good point. And yeah, not sure what would work best here with the else case, but I noticed that the remote admin change already throws on an invalid signature, so I think that's one reason this one made me think about it. Whatever you think is best there.

**Comment by mjheilmann** [comment]
I made the change, additionally checking the expiration within the constructor.  The now superfluous HasValidSignature and IsNotExpired flags are removed.

**Comment by appurist** [comment]
Very thorough and much simpler! Ready for merge.

**Pull request merged**
