### PR TITLE
Return of basicphysics

### PR DESCRIPTION
**Pull request by kf6kjg**
Everyone welcome our long-lost friend, BasicPhysics!

While BasicPhysics is nearly useless, it's the only tool to use when no other physics engine is available or working. 
It at least allows you to test that all the other code is running right!

This is important mainly on Linux where we don't at this time yet have a working PhysX implmentation.

### CODE REVIEW

**Comment by kf6kjg** [comment]
I'm not 100% confident that everything was implemented correctly, but assuming #19 and this are both merged, you should be able to bring a Linux install online.  I need to clean my local repository of uncommitted files and rebuild from scratch, double checking my assumptions, but I think I got everything.

**Comment by ddaeschler** [comment]
I don't want to merge #19 yet until we take a look at why the universal binary isn't working for SQLite as to avoid using two different libraries depending on the platform. However, this PR is unobtrusive and I'm going to give it a simple shakedown and if everything looks good I'll merge it.

**Comment by ddaeschler** [comment]
One issue:

In the prebuild.xml included in the PR, the target directory for the output is wrong. Once I fixed this the region started.

<Configuration name="Debug" platform="x64">
+        <Options>
+          <OutputPath>../../../../bin/</OutputPath>
+        </Options>
+      </Configuration>
+      <Configuration name="Release" platform="x64">
+        <Options>
+          <OutputPath>../../../../bin/</OutputPath>
+        </Options>
+      </Configuration>

should be 

<Configuration name="Debug" platform="x64">
+        <Options>
+          <OutputPath>../../../../bin/Physics</OutputPath>
+        </Options>
+      </Configuration>
+      <Configuration name="Release" platform="x64">
+        <Options>
+          <OutputPath>../../../../bin/Physics</OutputPath>
+        </Options>
+      </Configuration>

**Comment by ddaeschler** [comment]
When you get a chance, please patch that issue in your PR and I will apply it.

**Comment by kf6kjg** [comment]
Ah, I knew there was a likelihood of there being a miss somewhere: had not
enough time this morning before breakfast to do a complete cleanout and
test.  OK, I will fix that as soon as I can.

**Comment by ddaeschler** [comment]
No problem. Part of my job now is to test branches/PRs before merging to make sure stuff is working.

**Comment by kf6kjg** [comment]
Done, with also a style correction.  It looks like the default style is Visual Studio's.  I went and looked up Prebuild to see if it supported adding the MonoDevelop-specific rules for code formatting so that the developer (me) didn't have to reset that every time `runprebuild.sh` is executed. It doesn't, near as I can tell. Prebuild also seems to be a dead project: no movement since 2010.  Seems they figured that everyone's settled on MSBuild files and prebuild wasn't needed any more.

**Comment by ddaeschler** [comment]
Start up! Thanks!

**Pull request merged**
